### PR TITLE
WIP: CommunityModel

### PR DESCRIPTION
**Pull request by htpusa**
Let's make building and manipulating community models a bit easier.

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 63cd00ed is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 42ca4261 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 42ca4261 is formatted properly.

**Comment by stelmo** [comment]
I am continuing this in #696

**Comment by stelmo** [comment]
After merging #696, this PR is no longer needed!

**Pull request closed without merging**
