### PR TITLE
use the keyword arguments in new version of SBML

### PR DESCRIPTION
**Pull request by exaexa**
...hopefully ending the series of single-version SBML-compatibility fixes once for all.

This requires SBML 0.9.1 which is not released yet, will merge this after https://github.com/LCSB-BioCore/SBML.jl/pull/173 is tagged.

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit b6bd9479 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit a87b3c46 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 9629381a is formatted properly.

**Review by stelmo — APPROVED** [review]
🚀

**Pull request merged**
