### PR TITLE
Systematic model wrappers

### PR DESCRIPTION
**Pull request by exaexa**
This makes the model wrapping a bit more systematic. Currently there's the implementation for Serialized, I'll make one for the coupled CoreModel. Will see how that works.

Tests will probably keep failing for some time.

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 99dfa107 is formatted properly.

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit bd787b40 requires formatting!

Required formatting changes summary:
```
 src/base/macros/model_wrapper.jl | 27 ++++++++++++++++++++++++---
 1 file changed, 24 insertions(+), 3 deletions(-)
```

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit bd787b40 requires formatting!

Required formatting changes summary:
```
 src/base/macros/model_wrapper.jl | 27 ++++++++++++++++++++++++---
 1 file changed, 24 insertions(+), 3 deletions(-)
```

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit d3cda654 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit f43d77d6 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit df34cbff is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit c7180c45 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit c7180c45 is formatted properly.

**Review by stelmo — APPROVED** [review]

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 73fff04e is formatted properly.

**Pull request merged**
