### PR TITLE
start a github-based formatter

### PR DESCRIPTION
**Pull request by exaexa**
there's going to be some testing noise here

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit ae0887db is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 3afb40ee is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit ed28eda7 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit a0d19c90 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit d65be16d is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 2bd5f379 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit aad89fb1 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit e1ffb0b2 is formatted properly.

**Comment by exaexa** [comment]
I'll wrap this up eventually and open a new PR

**Pull request closed without merging**
