### PR TITLE
Add community functions for `StandardModel`

### PR DESCRIPTION
**Pull request by stelmo**
Add community functions for `StandardModel`

### CODE REVIEW

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit 9b82de10 requires formatting!

Required formatting changes summary:
```
 docs/src/notebooks/7_community_model.jl | 12 ++------
 src/reconstruction/community.jl         | 51 +++++++++++++++++++++++----------
 test/reconstruction/community.jl        | 12 ++------
 3 files changed, 40 insertions(+), 35 deletions(-)
```

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit 0361a5bd requires formatting!

Required formatting changes summary:
```
 docs/src/notebooks/7_community_model.jl | 12 ++------
 src/reconstruction/community.jl         | 51 +++++++++++++++++++++++----------
 test/reconstruction/community.jl        | 21 ++++----------
 3 files changed, 43 insertions(+), 41 deletions(-)
```

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit 7ce89c90 requires formatting!

Required formatting changes summary:
```
 docs/src/notebooks/7_community_model.jl | 12 +-----
 src/reconstruction/community.jl         | 45 +++++++++++++++--------
 test/reconstruction/community.jl        | 65 +++++++++++++++++++--------------
 3 files changed, 69 insertions(+), 53 deletions(-)
```

**Comment by stelmo** [comment]
Ended up making slightly more changes than anticipated

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit b008dcf1 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 86984060 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 3dad7a9b is formatted properly.

**Pull request merged**
