### PR TITLE
improve jsonmodel speed + some extra cleanup

### LINKED ISSUE #350: ⚡Conversion to `StandardModel` is slow, speed it up
Conversion to `StandardModel` is pretty slow, is there a way to speed it up?

### PR DESCRIPTION
**Pull request by exaexa**
Fixes #350 by caching.

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 7c96bbd9 is formatted properly.

**Review by stelmo — APPROVED** [review]

**Comment by stelmo** [comment]
Test code:
```julia
using COBREXA
using BenchmarkTools

@benchmark load_model(StandardModel, model_path)
```

Current conversion:
```julia
julia> @benchmark load_model(StandardModel, model_path)
BenchmarkTools.Trial: 
  memory estimate:  532.70 MiB
  allocs estimate:  30704399
  --------------
  minimum time:     7.763 s (2.35% GC)
  median time:      7.763 s (2.35% GC)
  mean time:        7.763 s (2.35% GC)
  maximum time:     7.763 s (2.35% GC)
  --------------
  samples:          1
  evals/sample:     1
```

This PR:
```julia
julia> @benchmark load_model(StandardModel, model_path)
BenchmarkTools.Trial: 
  memory estimate:  69.00 MiB
  allocs estimate:  1034802
  --------------
  minimum time:     223.278 ms (0.00% GC)
  median time:      256.775 ms (10.61% GC)
  mean time:        256.305 ms (11.40% GC)
  maximum time:     284.919 ms (17.28% GC)
  --------------
  samples:          20
  evals/sample:     1
```

I would say problem solved, thanks @exaexa 😄 🚀 👾 ✨ 🤖

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit f871a21b is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit f871a21b is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit b513e824 is formatted properly.

**Comment by laurentheirendt** [comment]
the currently displayed status check from git-r3 was a misfire and can be ignored 👍🏼

**Pull request merged**
