### PR TITLE
Add model annotation details

### PR DESCRIPTION
**Pull request by stelmo**
Since ObjectModel is the go-to model type, it should contain as much info as possible. The latest community standards paper actually lists some of the requirements that models should possess. Much of this information can be included already into the annotations fields for Reactions, Metabolites and Genes. However, the model lacks these fields. Here I just co-opt these for the model. The only drawback is that `Annotations` is just a dictionary, and to be miriam compliant it should be a vector of tuples like `Vector{Tuple{String, String, String}}`, I think. 

See paper: https://www.embopress.org/doi/full/10.15252/msb.20199235

### CODE REVIEW

**Review by exaexa — APPROVED** [review]
oh lovely

**Comment by exaexa** [comment]
PS it would be useful to probably make accessors for that, model_annotations and model_notes is OK. Not sure if that encodes to JSON but SBML should be very much OK

**Comment by stelmo** [comment]
cool, I will add accessors too!

**Review by exaexa — CHANGES_REQUESTED** [review]
- conversion function is discarding the information, can we fix it?
- I'll add this to SBMLModel (which actually supports this) and merge into this PR
- Does JSONModel support this?

**Comment by stelmo** [comment]
So unfortunately JSON model is not really standardized, I am not sure where they would store this kind of information. They do have an `id` field at the top level of the object, but that is about it....

**Comment by stelmo** [comment]
I just added what I could for JSONModel

**Comment by stelmo** [comment]
It is failing, but this is probably due to an SBML.jl problem

**Pull request merged**
