### PR TITLE
start the grand unification of remove_whatever

### LINKED ISSUE #362: ✨ Add in place versions of `remove_reaction` and `remove_metabolite` + plural variants for `CoreModel` and `StandardModel`
These functions are nice to have

### PR DESCRIPTION
**Pull request by exaexa**
This should eventually close #362

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit df758c69 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 9fa867e5 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 6f7d15c0 is formatted properly.

**Review by stelmo — APPROVED** [review]
Love it

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 870f492f is formatted properly.

**Pull request merged**
