### PR TITLE
Add convenience macro that loads all the functions in modules

### PR DESCRIPTION
**Pull request by stelmo**
A simple macro that just replaces
```julia
COBREXA.@using_all
```
with
```julia
using COBREXA.Types,
  COBREXA.Accessors,
  COBREXA.Analysis,
  COBREXA.Analysis.Modifications,
  COBREXA.Reconstruction,
  COBREXA.Reconstruction.Modifications,
  COBREXA.Utils,
  COBREXA.IO,
  COBREXA.Solver
```
when called.

### CODE REVIEW

**Comment by exaexa** [comment]
I'll have a look into module re-exports, sec

**Comment by exaexa** [comment]
Ha, this could help: https://github.com/simonster/Reexport.jl/blob/master/src/Reexport.jl
(we can simplify and intern the macro to avoid unnecessary dep)

**Review by exaexa — COMMENTED** [review]
I'm redoing this to an everymodule; macros here would be too wild

**Comment by exaexa** [comment]
@stelmo I got to the point where I have
```
WARNING: ignoring conflicting import of Reconstruction.Modifications into Everything
```

what do? :D

**Comment by stelmo** [comment]
That looks great!!

**Review by exaexa — APPROVED** [review]
I guess this is good now, let's merge so the rest of `next` can enjoy

**Pull request merged**
