### PR TITLE
Make the GRR parser a bit more robust

### PR DESCRIPTION
**Pull request by exaexa**

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit d473ee80 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 910bd857 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 910bd857 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit ab2637ee is formatted properly.

**Review by stelmo — APPROVED** [review]

**Pull request merged**
