### PR TITLE
document CodeModelCoupled reconstruction

### LINKED ISSUE #255: Fix docs of reconstructions/CoreModelCoupled
There are no function headers nor examples.

### PR DESCRIPTION
**Pull request by exaexa**
Closes #255

### CODE REVIEW

**Comment by htpusa** [comment]
Looks good to me. Could we merge #290 and then fix the rest of the docs for both `CoreModel`and `CoreModelCoupled` in another PR?

**Comment by exaexa** [comment]
ah okay I'll rebase this atop #290

**Comment by exaexa** [comment]
Ah 290 is in your repo :D

Btw re #290, can you just copypaste the docs there (and add it for the rest of the functions) ?

**Comment by htpusa** [comment]
You mean the docs from here? Sure, I'll do it.

**Comment by htpusa** [comment]
Merged into #307.

**Pull request closed without merging**
