### PR TITLE
Fixup & add SBML names

### PR DESCRIPTION
**Pull request by exaexa**

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 20835f6c is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit e68f2289 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit a84522fb is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit a89131b7 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit a89131b7 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit f82d9774 is formatted properly.

**Comment by exaexa** [comment]
because a split is needed I decided to merge this manually to #566  and continue with SBML-specific stuff elsewhere

**Pull request closed without merging**
