### PR TITLE
add SBML name accessors, bump SBML compat

### PR DESCRIPTION
**Pull request by exaexa**
This requires SBML bump to 0.9.3 which is not out yet (will add asap). Draft for now.

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 4576fdf6 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 1f46368b is formatted properly.

**Comment by exaexa** [comment]
Actually turned out to be SBML 0.10.0, should be ready now

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit d97366f6 is formatted properly.

**Review by stelmo — APPROVED** [review]

**Pull request merged**
