### PR TITLE
Solve convert(StandardModel, model::JSONModel) issue

### PR DESCRIPTION
**Pull request by josePereiro**
## Description

Hi, I'm trying to load a json model (download link: [elife-36842-supp10-v2.json](https://github.com/LCSB-BioCore/COBREXA.jl/files/14233094/elife-36842-supp10-v2.json)) from this [paper](https://doi.org/10.7554/eLife.36842).

The following code throw an error
```julia
using COBREXA
model = COBREXA.load_json_model(fn);
convert(StandardModel, model)
```

The error is related with the management of missing keys in the JSONModel... Mustly notes and annotations...

This pull request aim to solve them by returning default (empty) values when need it and generalizing the parsing mechanism. 

Saludos

#### Checklist

> Feel free to open PRs that do not satisfy the whole checklist. On the other
> hand, all these are required for merging.

- [x] All code is formatted with
  [JuliaFormatter](https://github.com/domluna/JuliaFormatter.jl)
  (run `using JuliaFormatter; format("path/to/COBREXA.jl");`)
- [x] Tests work (try with `]test COBREXA`)
- [x] All new functions have proper docstrings
- [x] Documentation builds correctly (try with `cd docs; julia make.jl`)

### CODE REVIEW

**Comment by stelmo** [comment]
Hi there! We are actually in the process of releasing COBREXA v2 (see [here](https://github.com/orgs/COBREXA/repositories)). We can definitely take a look at this PR, but you might want to consider porting it over [here](https://github.com/COBREXA/JSONFBCModels.jl). We split out the model loading interface from the analysis functions, and introduced a _much_ cleaner framework to make building complex models really easy.

**Comment by exaexa** [comment]
Hi @josePereiro, thanks a lot! I guess the patch looks OK, I'll try to merge this here (and take it apart into the new version's repositories) ASAP.

Among other things the (external) CI is currently a little dead; I'll check the stuff manually later.

For the "formatting" CI, if you click `details` there should be a patch to apply, but you don't need to care there (I'll do).

**Comment by josePereiro** [comment]
"Hi, it's good to hear about the progress on COBREXA v2. It will be great to have functionality separated into modules. I would suggest placing a notice in the COBREXA v1 package about this "news"; otherwise, it may seem like the project's development/maintenance status is lower.

I've opened a new [PR](https://github.com/COBREXA/JSONFBCModels.jl/pull/8) on JSONFBCModels. Most of the default functionality was already implemented, but the model at hand has deeper nested annotations, so the parser fails..."

**Comment by exaexa** [comment]
I tested this manually, all is OK. Thanks!

**Review by exaexa — APPROVED** [review]

**Comment by exaexa** [comment]
@josePereiro I will try to release this asap (not today, too late). If I forget about it PLEASE do feel free to remind me, I want to release this but in case it's not out next wednesday or so I just forgot. :D

**Pull request merged**
