### PR TITLE
simplify & unsurprise `set_optmodel_bound!`

### LINKED ISSUE #419: Change `set_optmodel_bound!` to have kwargs that do not override constraints
Currently `set_optmodel_bound!` takes two kwargs for `lb` and `ub`. This is tricky because if you do not supply one of them, it is easy to assume that the other one will not be modified in the model. However, this actually does get overwritten! Change this function so that:

1. If you supply both, then both are changed
2. If you supply either `lb` or `ub`, then the other one does not get changed

### PR DESCRIPTION
**Pull request by exaexa**
Closes #419

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 38035c85 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit a2ea9dc6 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 8d85d8b6 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 8d85d8b6 is formatted properly.

**Review by stelmo — APPROVED** [review]
excellent!

**Pull request merged**
