### PR TITLE
docs badges & acks

### LINKED ISSUE #250: add backlink from docs
**Describe the solution you'd like**
an easy clickthrough from docs main page to git repo

**Describe alternatives you've considered**
none, it would be best to find how/if others do it

**Additional context**
thanks @Trefex

### PR DESCRIPTION
**Pull request by exaexa**
cross-repo PR! :hammer: 

Fixes #250, also reacts to the PMC comments we got about all landing pages.

### CODE REVIEW

**Review by laurentheirendt — CHANGES_REQUESTED** [review]
I think it would be best if we had the same ack's in `README.md` than in `index-template.md`

**Comment by exaexa** [comment]
> I think it would be best if we had the same ack's in `README.md` than in `index-template.md`

I can cut it out as with the guide, the main problem is that the "main" part of the acks (the logos) are not "portable" b/c links will break (or should I just put absolute URLs there?)

**Comment by laurentheirendt** [comment]
maybe then absolute URLs are best ...

**Comment by laurentheirendt** [comment]
or we replace `assets/` properly during the documentation generation - I'd prefer that actually

**Comment by laurentheirendt** [comment]
in consideration of #262, can you open from a branch from the upstream repo?

**Pull request closed without merging**
