### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by stelmo**
Docs broke

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit a32ff264 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit e99a531c is formatted properly.

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit 194f3f5c requires formatting!

Required formatting changes summary:
```
 docs/src/notebooks/2_finding_balance.jl | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
```

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 7585e9e8 is formatted properly.

**Review by exaexa — APPROVED** [review]
:crossed_fingers:

**Pull request merged**
