### PR TITLE
Re-organize everything into modules to make discoverability easier

### PR DESCRIPTION
**Pull request by stelmo**
I also got rid of the autoloading "feature", it gets in the way more than it helps... 

Possible modules include:
1. Common
2. IO 
3. Analysis
4. Reconstruction

Open questions:
1. How many levels deep do we want to go? Like `COBREXA.Common.Types` or just `COBREXA.Common`
2.  tbd

### CODE REVIEW

**Comment by stelmo** [comment]
@exaexa I am having trouble with the macros, they don't exist when they need to, do you know how to make the current state of the PR compile? Also, how do I use `FromFile` correctly? Or is the multiple importing thing okay?

**Comment by stelmo** [comment]
Currently the problem is with the wrappers. They have helper functions (currently located in `types/wrappers/SMomentModel.jl` or `types/wrappers/GeckoModel.jl`) which require the accessors to be used, but they are not accessors... :/

**Comment by stelmo** [comment]
Instead use #674

**Comment by exaexa** [comment]
:headstone:  tho.

**Pull request closed without merging**
