### PR TITLE
pFBA pipe

### PR DESCRIPTION
**Pull request by stelmo**
Adds a basic pipe-able pFBA variant. Should play nicely with more interesting model types, e.g. enzyme constrained etc.
```julia
gm_changed_bound =
    model |>
    with_changed_bound("BIOMASS_Ecoli_core_w_GAM", lower_bound = growth_lb) |>
    with_enzyme_constraints(
        gene_product_mass_group_bound = Dict(
            "uncategorized" => total_gene_product_mass,
        ),
    )

pfba_sol =
  gm_changed_bound |>
  with_parsimonious_solution(:enzyme) |>
  flux_balance_analysis(Clarabel.Optimizer)
```
@exaexa what do you think?

### CODE REVIEW

**Comment by stelmo** [comment]
NOTE: variables are not the semantic variables!

**Comment by stelmo** [comment]
this poses problems for MOMA too

**Comment by stelmo** [comment]
and also for pFBA in general

**Review by exaexa — COMMENTED** [review]
ok now we have wrapper architecture nicely split off and there's the "generic" QP objective wrappers. I guess pFBA can be done over these as well, right?

**Review by exaexa — APPROVED** [review]
awright

**Pull request merged**
