### PR TITLE
add an example for objective_envelope

### PR DESCRIPTION
**Pull request by exaexa**
## Description

Example makes it more clear

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 5bb05b29 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 8ed7d68d is formatted properly.

**Review by stelmo — APPROVED** [review]

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 69340c9a is formatted properly.

**Review by htpusa — APPROVED** [review]

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 8a62eb6e is formatted properly.

**Pull request merged**
