### PR TITLE
draft: comments on PRs from formatting bot

### PR DESCRIPTION
**Pull request by laurentheirendt**
Let's see what happens 😄

### CODE REVIEW

**Comment by exaexa** [comment]
it went boom :sob:

**Comment by laurentheirendt** [comment]
ha yes, might take a few tries - sorry for the spam 😃

**Comment by cylon-x** [comment]
There are files that need formatting.

**Comment by cylon-x** [comment]
There are files that need formatting.

**Comment by cylon-x** [comment]
There are files that need formatting.

**Comment by cylon-x** [comment]
There are files that need formatting.

**Comment by cylon-x** [comment]
There are files that need formatting.

**Comment by cylon-x** [comment]
There are files that need formatting.

**Comment by cylon-x** [comment]
All files are formatted properly :white_check_mark:

**Comment by laurentheirendt** [comment]
closing in favor of #371

**Pull request closed without merging**
