### PR TITLE
minimize the change_bound generator macro

### PR DESCRIPTION
**Pull request by exaexa**

### CODE REVIEW

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit 0075b64f requires formatting!

Required formatting changes summary:
``` src/reconstruction/CoreModel.jl         | 14 ++++++++++++--
 test/reconstruction/CoreModel.jl        | 32 ++++++--------------------------
 test/reconstruction/CoreModelCoupled.jl | 18 ++++--------------
 test/reconstruction/StandardModel.jl    | 22 ++++------------------
 4 files changed, 26 insertions(+), 60 deletions(-)
```

**Comment by exaexa** [comment]
I erased the cylon-x formatting comment because he tricked me into forgetting to commit the format I had ready.

Shame.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 412a0061 is formatted properly.

**Comment by exaexa** [comment]
> green_circle  Commit [412a006](https://github.com/LCSB-BioCore/COBREXA.jl/commit/412a00613253788f471b9d3ec2a5da2bb12640f4) is formatted properly.

Thank you cylon, no more tricks!

**Review by stelmo — APPROVED** [review]
This is amazing 😲

**Pull request merged**
