### PR TITLE
Fix error with screen and `unregister`

### PR DESCRIPTION
**Pull request by stelmo**
Getting a strange error when using `screen` and pFBA. Fixing:
```julia
ERROR: On worker 32:
UndefVarError: unregister not defined
Stacktrace:
  [1] getproperty
    @ ./Base.jl:26 [inlined]
  [2] #parsimonious_flux_balance_analysis#337
    @ ~/.julia/packages/COBREXA/nwDhX/src/analysis/parsimonious_flux_balance_analysis.jl:88
```

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 9314bed6 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 5cae6c88 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 5cae6c88 is formatted properly.

**Comment by exaexa** [comment]
Hm now this is interesting. Why are the prefixes even there?

Might be the case that we'd need to remove from more places, see here:
```sh
 $ grep \ COBREXA\\. src -r
src/analysis/modifications/optimizer.jl:    (model, opt_model) -> COBREXA.JuMP.set_objective_sense(opt_model, objective_sense)
src/analysis/modifications/optimizer.jl:    (model, opt_model) -> COBREXA.JuMP.set_optimizer(opt_model, optimizer)
src/analysis/modifications/optimizer.jl:        COBREXA.JuMP.set_optimizer_attribute(opt_model, attribute_key, value)
src/analysis/flux_balance_analysis.jl:    COBREXA.JuMP.optimize!(opt_model)
src/analysis/parsimonious_flux_balance_analysis.jl:    original_objective = COBREXA.JuMP.objective_function(opt_model)
src/analysis/parsimonious_flux_balance_analysis.jl:        COBREXA.JuMP.delete(opt_model, pfba_constraint)
src/analysis/parsimonious_flux_balance_analysis.jl:        COBREXA.JuMP.unregister(opt_model, :pfba_constraint)
grep: src/analysis/.parsimonious_flux_balance_analysis.jl.swp: binary file matches
src/base/constants.jl:const MAX_SENSE = COBREXA.MOI.MAX_SENSE
src/base/constants.jl:const MIN_SENSE = COBREXA.MOI.MIN_SENSE
src/base/solver.jl:    optimization_model = COBREXA.JuMP.Model(optimizer)
src/base/solver.jl:    COBREXA.JuMP.optimize!(optimization_model)
src/base/solver.jl:    COBREXA.JuMP.termination_status(optmodel) in [MOI.OPTIMAL, MOI.LOCALLY_SOLVED] ? true :
```

**Review by exaexa — APPROVED** [review]
so let's hope this doesn't break on HPCs

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 56158f9f is formatted properly.

**Comment by stelmo** [comment]
All prefixes have been removed

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 8c4d50c4 is formatted properly.

**Pull request merged**
