### PR TITLE
docker build from gitlab

### PR DESCRIPTION
**Pull request by exaexa**
the venerable github is unable to trigger on bot-tagged releases, so we migrate to gitlabs.

### CODE REVIEW

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit df4887f9 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 60192627 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit f882020a is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit c84b2838 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 58717f57 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 182682f0 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 436ef569 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 6883db6d is formatted properly.

**Review by laurentheirendt — APPROVED** [review]
❤️

**Pull request merged**
