### PR TITLE
Added `reaction_equation` function and tests

### PR DESCRIPTION
**Pull request by stelmo**
Does this:
```julia
julia> req = Dict("coa_c" => -1, "for_c" => 1, "accoa_c" => 1, "pyr_c" => -1)
Dict{String, Int64} with 4 entries:
  "coa_c"   => -1
  "for_c"   => 1 
  "accoa_c" => 1 
  "pyr_c"   => -1

julia>  rstr_out = reaction_equation(req)
"coa_c + pyr_c = for_c + accoa_c"
```

### CODE REVIEW

**Comment by stelmo** [comment]
This closes #394

**Review by exaexa — APPROVED** [review]
looks OK. One thing to possibly change would be the name of the function, alternatives could IMHO go towards `stoichiometry_string` or `show_stoichiometry` or so.

**Comment by stelmo** [comment]
Yeah, I like `stoichiometry_string` the most :] changing

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit e66d473a is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit be517c3d is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 7759085b is formatted properly.

**Pull request merged**
