### PR TITLE
Extend simplified enzyme model to include multiple capacity constraints

### PR DESCRIPTION
**Pull request by stelmo**

### CODE REVIEW

**Review by exaexa — CHANGES_REQUESTED** [review]
pls rebase this atop the pfba PR (and merge into that one) since the wrappers moved.

other than that I guess it looks okay.

**Comment by stelmo** [comment]
No idea why `next` is not failing on this test :/ the solver seems to give different values for the exact same problem... Changed the solver expected solution to report fewer decimal places

**Comment by stelmo** [comment]
Will rebase on #773

**Comment by stelmo** [comment]
\format

**Comment by stelmo** [comment]
Finally fixed this! Should also fix the broken things in `next`

**Review by exaexa — APPROVED** [review]
kewl

**Pull request merged**
