### PR TITLE
docfixes

### PR DESCRIPTION
**Pull request by exaexa**
this closes many issues found during the docs deployment

### CODE REVIEW

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit 5ead824e requires formatting!

Required formatting changes summary:
```
 docs/make.jl | 18 ++++++------------
 1 file changed, 6 insertions(+), 12 deletions(-)
```

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit f0b18a03 requires formatting!

Required formatting changes summary:
```
 docs/make.jl | 18 ++++++------------
 1 file changed, 6 insertions(+), 12 deletions(-)
```

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit 69ba2bd7 requires formatting!

Required formatting changes summary:
```
 docs/make.jl | 18 ++++++------------
 1 file changed, 6 insertions(+), 12 deletions(-)
```

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit 974b7f55 requires formatting!

Required formatting changes summary:
```
 docs/make.jl | 18 ++++++------------
 1 file changed, 6 insertions(+), 12 deletions(-)
```

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit 32d882f7 requires formatting!

Required formatting changes summary:
```
 docs/make.jl | 18 ++++++------------
 1 file changed, 6 insertions(+), 12 deletions(-)
```

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit ea40a262 is formatted properly.

**Review by laurentheirendt — APPROVED** [review]

**Pull request merged**
