### PR TITLE
Use Makie instead of Plots

### PR DESCRIPTION
**Pull request by stelmo**
I like Makie more :/

### CODE REVIEW

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit 9ec83298 requires formatting!

Required formatting changes summary:
```
 docs/src/notebooks/6_screening.jl | 24 ++++++++++++++++++------
 1 file changed, 18 insertions(+), 6 deletions(-)
```

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit da87177b is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit da87177b is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 70edc80f is formatted properly.

**Review by laurentheirendt — APPROVED** [review]

**Pull request merged**
